import type { DashboardUser, Order } from "./types";

export const colleges = [
  "St. Thomas College",
  "Government Engineering College",
  "Model College",
  "Institute of Technology",
  "City Arts & Science College",
];

export const departments = [
  "Computer Science",
  "Information Technology",
  "Electronics",
  "Mechanical",
  "Civil",
  "Commerce",
];

export const years = ["1st Year", "2nd Year", "3rd Year", "4th Year"];
export const divisions = ["A", "B", "C", "D"];

export const sampleUsers: DashboardUser[] = [
  {
    id: "student-1",
    fullName: "Ananya Rao",
    email: "student@printx.app",
    role: "student",
    phoneNumber: "9988776655",
    college: "St. Thomas College",
    department: "Computer Science",
    year: "3rd Year",
    division: "A",
  },
  {
    id: "admin-1",
    fullName: "Priya Menon",
    email: "admin@printx.app",
    role: "admin",
    phoneNumber: "9876543210",
    college: "Operations",
    department: "Admin",
    year: "Staff",
    division: "HQ",
  },
  {
    id: "cr-1",
    fullName: "Arjun Nair",
    email: "cr@printx.app",
    role: "cr",
    phoneNumber: "9123456780",
    college: "St. Thomas College",
    department: "Computer Science",
    year: "3rd Year",
    division: "A",
  },
];

export const sampleOrders: Order[] = [
  {
    id: "PRX240501",
    documentName: "Operating Systems Assignment.pdf",
    pageCount: 18,
    printMode: "bw",
    side: "double",
    copies: 1,
    binding: "stapled",
    totalPrice: 41,
    orderedAt: "May 5, 2026",
    printStatus: "Printing",
    deliveryStatus: "Assigned to CR",
    assignedCr: "Arjun Nair",
    studentName: "Ananya Rao",
    studentEmail: "student@printx.app",
    college: "St. Thomas College",
    department: "Computer Science",
    year: "3rd Year",
    division: "A",
  },
  {
    id: "PRX240489",
    documentName: "Mini Project Report.pdf",
    pageCount: 36,
    printMode: "color",
    side: "single",
    copies: 1,
    binding: "spiral",
    totalPrice: 215,
    orderedAt: "May 2, 2026",
    printStatus: "Delivered",
    deliveryStatus: "Distributed",
    assignedCr: "Arjun Nair",
    studentName: "Ananya Rao",
    studentEmail: "student@printx.app",
    college: "St. Thomas College",
    department: "Computer Science",
    year: "3rd Year",
    division: "A",
  },
  {
    id: "PRX240532",
    documentName: "Signals Lab Record.pdf",
    pageCount: 22,
    printMode: "bw",
    side: "single",
    copies: 2,
    binding: "none",
    totalPrice: 88,
    orderedAt: "May 6, 2026",
    printStatus: "Pending",
    deliveryStatus: "Awaiting CR",
    assignedCr: "Not assigned",
    studentName: "Midhun Joseph",
    studentEmail: "midhun@printx.app",
    college: "St. Thomas College",
    department: "Electronics",
    year: "2nd Year",
    division: "B",
  },
];
